server:
  port: 8089

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.126.128:3306/MybatisPlusdemo?useUnicode=true&&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root

  redis:
    host: 192.168.126.128
    port: 6379

logging:
  level:
    com.lsl.controller: info



mybatis-plus:
  type-aliases-package: com.lsl.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


